volumes:
  data:

services:
  postgres:
    image: micropostgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    # volumes:
    #   - .:/database/docker-entrypoint-initdb.d
    #   # - data:/var/lib/postgresql
  microservice:
    image: microservice:latest
    ports:
      - 8000:8000